### ISSUE TITLE
prisoner_env.py generate_policy_heatmap

### ISSUE THREAD

**Issue by Yuxin916** [CORE-Robotics-Lab/Opponent-Modeling#1]
Hi, 
Thank you for your work! 

i was trying to run through this gym environment you provided first. In prisoner_env.py, 
if __name__ == "__main__":
    np.random.seed(20)
    p = PrisonerBothEnv()
    p.generate_policy_heatmap(p.reset(), policy='rand', end=True)

Inside this generate_policy_heatmap function, line 1438: 
observation, reward, done, _ = self.step(action)

The self.step here is missing 1 required positional argument: 'blue_action'. 
Could you please help with it? 

In addition, i noticed that there exists PrisonerBothEnv and PrisonerBlueEnv. why in collect demostration file, only use the PrisonerBlueEnv?

Looking forwar dto your reply

Best regards

**Comment by xunil17** [comment]
Hi,
Thank you for taking the time to checkout our work!

This function's purpose in the past was to produce a heatmap predicting the adversary from a given policy by rolling out the policy in the environment. If you would like to use it, please move the function under class `PrisonerEnv` in the prisoner_perspective_envs and use it like so:

```  
    env = PrisonerBothEnv()
    policy = BlueHeuristic(env, debug=False)
    env = PrisonerEnv(env, policy)
    env.generate_policy_heatmap(env.reset(), policy='rand', end=True)
```

However, please note that this function has been deprecated and may not produce exactly what you are looking for.

Our base environment is the PrisonerBothEnv class. This handles actions from both a policy for the blue team and red team. The PrisonerBlueEnv and PrisonerEnv are essentially wrappers for the PrisonerBothEnv class such that given the policy of the other team, we just return the observations for the desired team (red or blue). In our tracking work, this does not make much of a difference in collect demonstrations as we are using heuristics for both teams.

In our [adjacent work](https://arxiv.org/pdf/2306.11301.pdf), we train a MARL policy to control the Blue Team. In this case, we use the PrisonerBlueEnv. Similarly, if you wanted to control the red agent, the PrisonerEnv class would be best suited.

Thanks!
Sean

**Comment by Yuxin916** [comment]
Thank you for your fast reply! That's very helpful!!!!

I was indeed very interested in train a MARL policy to control the Blue Team. And the evader's policy i want to make it RRTStarAdversarialAvoid. My research interest is to use MARL to enhance coodination under this adversial tracking predator-prey environment. Therefore i found your work really related and helpful! 
May i ask is it possible to open-source the code of the paper you provided? [Paper](https://arxiv.org/pdf/2306.11301.pdf). If not, is it possible to discuss more details through email?

Best regards

**Comment by xunil17** [comment]
Yep, we're actively working on open sourcing that codebase and will let you know when it is published online!
