### ISSUE TITLE
Evader's detection range

### ISSUE THREAD

**Issue by Yuxin916** [CORE-Robotics-Lab/Opponent-Modeling#2]
Hi Thank you again for your work! 
i have a quenstion regarding how the evader detect the searcher team. In file Prison_Escape/environment/fugitive.py, the detect function, 

    def detect(self, location_object, object_instance):
        """
        Determine detection of an object based on its location and type of the object
        The fugitive's detection of other parties is different other parties' detection of the fugitive as given in the "detection ranges.xlsx".
        The fugitive's detection of other parties depends on what the party is.
        :param location_object:
        :param object_instance: the instance referred to the object the fugitive is detecting.
        :return: [b,x,y] where b is a boolean indicating detection, and
        [x,y] is the location of the object in world coordinates if b=True,
        [x,y]=[-1,-1] if b=False
        """
        if isinstance(object_instance, Prison_Escape.environment.helicopter.Helicopter):
            self.detection_object_type_coefficient = 0.5
            return DetectionObject.detect(self, location_object, 8)
        elif isinstance(object_instance, Prison_Escape.environment.search_party.SearchParty):
            self.detection_object_type_coefficient = 0.75
            return DetectionObject.detect(self, location_object, 3)
        else:
            raise NotImplementedError

Why the DetectionObject.detect(self, location_object, 8) and DetectionObject.detect(self, location_object, 3) be 8 and 3? i thought it should match the search party and helicopter's speed defined in .yaml file. 

In addition, sorry i did not read through the whole codebase, may i ask how do you define the detection range (radius) of each agent? including the helicopter, catcher and also evader? What is the meaning of "The detection rates are adapted by changing the detection radius of the pursuit agents"?

Thank you!

**Comment by xunil17** [comment]
Hi,

Yes, these are hard coded for game-balance of the environment. In `Prison_Escape/environment/configs/balance_game.yaml`, there is a detection factor that is a constant we multiply. Raising this value increases the detection radius of the agents. The detection radius has an inner circle which represents the area where there is 100% certainty and an outer circle where the probability of detection decays to 0.

**Comment by Yuxin916** [comment]
Hi thank you for the reply.
